server:
  port: 8888
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: path_route # 根据url路径路由，测试地址：http://xxxx:xx/gateway/front-server1/ribbon-demo/demo2
          predicates: # 断言
            - Path=/gateway/** # 地址匹配，PathRoutePredicateFactory
          filters: # 过滤器
            - StripPrefix=1 # StripPrefixGatewayFilterFactory
            - MyDefine=Hello World # MyDefineGatewayFilterFactory
          uri: http://127.0.0.1:8080 # 转发到的目标服务
        - id: cookie_route # 根据cookie路由，测试地址：http://xxxx:xx/
          predicates:
            - Cookie=cookie_key,cookie_val # cookie匹配，CookieRoutePredicateFactory（cookie_key=cookie_val）
          uri: https://www.baidu.com
        - id: lb_route
          predicates:
            - Path=/lb/**
          filters:
            - StripPrefix=1
          uri: lb://order-server2 # 负载均衡
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  sleuth:
    annotation:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka

logging:
  level:
    org.springframework.cloud.sleuth: debug